### ISSUE TITLE
It seems there is no way to get google login user response.

### ISSUE THREAD

**Issue by tom10271** [abacritt/angular4-social-login#14] opened 2017-10-11 03:12 UTC
I need the access token inside the response

https://developers.google.com/identity/sign-in/web/reference#gapiauth2authresponse

**Comment by jaibatrik** [comment] 2017-10-12 06:42
Duplicate of #10. I'll try to work on this over weekend. You are also welcome to submit a PR.

**Closed by jaibatrik** 2017-10-12 06:42 UTC
